Repository sap-labs-france/ev-server, pull requests merged in 2021-07, with the labels that each got.

#2634 Billing - periodic operation - some fixes
  src/integration/billing/BillingIntegration.ts
  src/integration/billing/stripe/StripeBillingIntegration.ts
  test/api/BillingStripeTestData.ts
  test/api/BillingTest.ts
Labels: enhancement

#2650 billing - prevent STRIPE customers deletion
  src/integration/billing/stripe/StripeBillingIntegration.ts
  src/utils/FeatureToggles.ts
Labels: bug

#2678 minor change
  src/utils/TemplateManager.ts
Labels: enhancement

#2683 saveTransactionBillingData is now called
  src/async-task/tasks/BillTransactionAsyncTask.ts
  src/integration/billing/BillingIntegration.ts
  src/integration/billing/stripe/StripeBillingIntegration.ts
Labels: performance
