Repository sap-labs-france/ev-server, pull requests merged in 2022-07, with the labels that each got.

#3683 user - postpone sync with stripe
  src/server/rest/v1/service/AuthService.ts
Labels: enhancement

#3703 bp - onboarding flow rework
  src/integration/billing/BillingIntegration.ts
  src/integration/billing/stripe/StripeBillingIntegration.ts
  src/server/rest/v1/router/util/UtilRouter.ts
  src/server/rest/v1/service/BillingService.ts
  src/types/Server.ts
  src/utils/Utils.ts
  test/api/BillingTestHelper.ts
  test/api/client/BillingApi.ts
Labels: enhancement

#3713 bp - tests - troubleshooting - dump last errors
  test/api/BillingTestHelper.ts
Labels: qa

#3715 bp - tax rate per account
  src/assets/server/rest/v1/docs/e-mobility-oas.json
  src/assets/server/rest/v1/schemas/billing/billing-create-account.json
  src/authorization/AuthorizationsDefinition.ts
  src/integration/billing/BillingIntegration.ts
  src/integration/billing/stripe/StripeBillingIntegration.ts
  src/server/rest/v1/service/BillingService.ts
  src/storage/mongodb/BillingStorage.ts
  src/types/Billing.ts
  test/api/BillingPlatformTest.ts
  test/api/BillingTestHelper.ts
  test/api/StripeTestHelper.ts
Labels: enhancement

#3722 BP - Rework - Generate transfers from Transactions (not from Invoices)
  package.json
  src/assets/server/rest/v1/docs/e-mobility-oas.json
  src/async-task/AsyncTaskManager.ts
  src/async-task/tasks/PrepareInvoiceTransferAsyncTask.ts
  src/authorization/AuthorizationsDefinition.ts
  src/integration/billing/BillingHelpers.ts
  src/integration/billing/BillingIntegration.ts
  src/integration/billing/stripe/StripeBillingIntegration.ts
  src/locking/LockingHelper.ts
  src/scheduler/tasks/BillingPeriodicOperationTask.ts
  src/scheduler/tasks/DistpatchCollectedFundsTask.ts
  src/server/rest/v1/service/BillingService.ts
  src/storage/mongodb/BillingStorage.ts
  src/storage/mongodb/TransactionStorage.ts
  src/types/AsyncTask.ts
  src/types/Billing.ts
  src/types/Server.ts
  src/types/TaskConfig.ts
  src/types/Transaction.ts
  test/api/BillingPlatformTest.ts
  test/api/BillingTest.ts
  test/api/BillingTestHelper.ts
  test/api/StripeTestHelper.ts
  test/factories/BillingFactory.ts
Labels: feature

#3718 Billing Platform - Assign AccountData to Company
  src/assets/server/rest/v1/schemas/billing/billing-create-account.json
  src/assets/server/rest/v1/schemas/billing/billing-transfers-get.json
  src/assets/server/rest/v1/schemas/company/company-create.json
  src/assets/server/rest/v1/schemas/company/company-update.json
  src/authorization/AuthorizationsDefinition.ts
  src/server/rest/v1/router/api/BillingRouter.ts
  src/server/rest/v1/service/BillingService.ts
  src/server/rest/v1/service/CompanyService.ts
  src/server/rest/v1/service/SiteService.ts
  src/storage/mongodb/BillingStorage.ts
  src/storage/mongodb/CompanyStorage.ts
  src/types/Billing.ts
  test/api/BillingPlatformTest.ts
  test/api/BillingTestHelper.ts
Labels: enhancement

#3769 redirect - v2 - moved temporarily
  src/server/rest/v1/service/CommonService.ts
  src/server/rest/v1/service/SessionHashService.ts
Labels: enhancement
