Repository sap-labs-france/ev-server, pull requests merged in 2022-09, with the labels that each got.

#3851 CPO - Pull Tokens = Do not get tags when there is nothing to do!
  src/client/ocpi/CpoOCPIClient.ts
Labels: performance

#3854 test perf cleanup
  package.json
  test/api/ChargingStationTemplateTest.ts
  test/api/client/CentralServerService.ts
Labels: tests

#3846 Migrate transaction to abac
  package.json
  src/authorization/AuthorizationsDefinition.ts
  src/server/rest/v1/service/AuthorizationService.ts
  src/server/rest/v1/service/TransactionService.ts
  src/server/rest/v1/service/UtilsService.ts
  src/storage/mongodb/TransactionStorage.ts
  src/types/Authorization.ts
  src/types/DataResult.ts
  src/types/GlobalType.ts
  src/types/Transaction.ts
  src/utils/Utils.ts
  test/api/TransactionCommonTests.ts
  test/api/TransactionTest.ts
Labels: enhancement

#3874 emails - FR translation
  src/assets/i18n/cs.json
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
  src/assets/i18n/fr.json
  src/assets/i18n/it.json
  src/assets/i18n/pt.json
  src/assets/server/notification/email/en/compute-and-apply-charging-profiles-failed.json
  src/assets/server/notification/email/en/end-of-charge.json
  src/assets/server/notification/email/en/ocpi-patch-status-error.json
  src/assets/server/notification/email/en/optimal-charge-reached.json
  src/assets/server/notification/email/en/request-password.json
  src/assets/server/notification/email/es/compute-and-apply-charging-profiles-failed.json
  src/assets/server/notification/email/pt/compute-and-apply-charging-profiles-failed.json
  src/notification/email/EMailNotificationTask.ts
  src/types/UserNotifications.ts
  test/api/EmailTest.ts
Labels: enhancement
