Repository sap-labs-france/ev-server, pull requests merged in 2022-06, with the labels that each got.

#3570 Billing Platform as Tenant component
  src/assets/schemas/tenant/tenant-components.json
  src/assets/server/rest/v1/schemas/setting/setting-billing-platform-set.json
  src/server/rest/v1/service/BillingService.ts
  src/server/rest/v1/service/SettingService.ts
  src/server/rest/v1/service/UtilsService.ts
  src/server/rest/v1/validator/SettingValidator.ts
  src/types/Setting.ts
  src/types/Tenant.ts
  test/api/BillingTest.ts
  test/api/BillingTestHelper.ts
  test/api/ComponentActivationTenantTest.ts
  test/api/context/ContextDefinition.ts
Labels: feature

#3584 Billing > Assign subaccounts to sites and/or companies
  src/assets/schemas/billing/billing-subaccount.json
  src/assets/server/rest/v1/docs/e-mobility-oas.json
  src/assets/server/rest/v1/schemas/billing/billing-sub-account-get.json
  src/assets/server/rest/v1/schemas/billing/billing-sub-accounts-get.json
  src/assets/server/rest/v1/schemas/company/company-create.json
  src/assets/server/rest/v1/schemas/company/company-update.json
  src/assets/server/rest/v1/schemas/site/site-create.json
  src/assets/server/rest/v1/schemas/site/site-update.json
  src/authorization/AuthorizationsDefinition.ts
  src/integration/billing/stripe/StripeBillingIntegration.ts
  src/server/rest/v1/router/api/BillingRouter.ts
  src/server/rest/v1/service/AuthorizationService.ts
  src/server/rest/v1/service/BillingService.ts
  src/server/rest/v1/service/CompanyService.ts
  src/server/rest/v1/service/SiteService.ts
  src/server/rest/v1/service/UtilsService.ts
  src/server/rest/v1/validator/BillingValidatorRest.ts
  src/storage/mongodb/BillingStorage.ts
  src/storage/mongodb/CompanyStorage.ts
  src/storage/mongodb/SiteStorage.ts
  src/types/Authorization.ts
  src/types/Billing.ts
  src/types/Company.ts
  src/types/DataResult.ts
  src/types/Server.ts
  src/types/Site.ts
  src/types/requests/HttpBillingRequest.ts
  src/validator/SchemaValidator.ts
  test/api/BillingTest.ts
  test/api/client/BillingApi.ts
Labels: feature

#3590 Billing > send onboarding endpoint
  src/authorization/AuthorizationsDefinition.ts
  src/server/rest/v1/router/api/BillingRouter.ts
  src/server/rest/v1/router/util/UtilRouter.ts
  src/server/rest/v1/service/BillingService.ts
  src/types/Authorization.ts
  src/types/Server.ts
  test/api/BillingTest.ts
  test/api/client/BillingApi.ts
  test/api/client/utils/CrudApi.ts
Labels: feature

#3648 fix - billingInvoice.user is not set
  src/integration/billing/BillingIntegration.ts
  src/notification/NotificationTask.ts
  src/notification/email/EMailNotificationTask.ts
  src/notification/remote-push-notification/RemotePushNotificationTask.ts
  src/types/UserNotifications.ts
Labels: bug

#3657 bp - transfers - projected fields
  src/authorization/Authorizations.ts
  src/authorization/AuthorizationsDefinition.ts
  src/storage/mongodb/BillingStorage.ts
  src/storage/mongodb/DatabaseUtils.ts
  src/types/Billing.ts
Labels: enhancement

#3639 feat(billing-platform): transfer finalization endpoint
  src/assets/server/rest/v1/docs/e-mobility-oas.json
  src/assets/server/rest/v1/schemas/billing/billing-transfer-finalize.json
  src/authorization/AuthorizationsDefinition.ts
  src/server/rest/v1/router/api/BillingRouter.ts
  src/server/rest/v1/service/AuthorizationService.ts
  src/server/rest/v1/service/BillingService.ts
  src/server/rest/v1/validator/BillingValidatorRest.ts
  src/types/Authorization.ts
  src/types/Server.ts
  src/types/requests/HttpBillingRequest.ts
  test/api/BillingTest.ts
  test/api/client/BillingApi.ts
Labels: enhancement
